#!/bin/bash

# WeChat Copilot 项目整理和备份脚本

# 创建时间戳
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

echo "🔄 开始项目整理和备份... ($TIMESTAMP)"

echo "----------------------------------------"
echo "备份原始内容到 edit.logs"
echo "----------------------------------------"

# 备份现有文件内容到日志
{
    echo "======= 备份时间: $TIMESTAMP ========"
    echo ""
    
    if [ -f "/home/neogh/wechat_copilot/README.md" ]; then
        echo "======= 原始 README.md 内容 ========"
        cat "/home/neogh/wechat_copilot/README.md" 2>/dev/null || echo "文件为空或不存在"
        echo ""
    fi
    
    if [ -f "/home/neogh/wechat_copilot/ProjectFramework.md" ]; then
        echo "======= 原始 ProjectFramework.md 内容 ========"
        cat "/home/neogh/wechat_copilot/ProjectFramework.md" 2>/dev/null || echo "文件为空或不存在"
        echo ""
    fi
    
    if [ -f "/home/neogh/wechat_copilot/tree.md" ]; then
        echo "======= 原始 tree.md 内容 ========"
        cat "/home/neogh/wechat_copilot/tree.md" 2>/dev/null || echo "文件为空或不存在"
        echo ""
    fi
    
    if [ -f "/home/neogh/wechat_copilot/INSTALL.md" ]; then
        echo "======= 原始 INSTALL.md 内容 ========"
        cat "/home/neogh/wechat_copilot/INSTALL.md" 2>/dev/null || echo "文件为空或不存在"
        echo ""
    fi
    
} >> "/home/neogh/wechat_copilot/edit.logs"

echo "✅ 原始内容已备份到 edit.logs"

echo ""
echo "----------------------------------------"
echo "生成新的文档文件"
echo "----------------------------------------"

# 生成新的 tree.md - 项目文件结构
{
    echo "# WeChat Copilot 项目文件结构"
    echo ""
    echo "\`\`\`"
    cd /home/neogh/wechat_copilot
    find . -type f -not -path "*/node_modules/*" -not -path "*/\.git/*" -not -path "*/\.venv/*" -not -path "*/\_pycache__/*" -not -path "*/\.pytest_cache/*" -not -path "*/\.DS_Store" -not -path "*\.log" -not -path "*~" | sort
    echo "\`\`\`"
} > "/home/neogh/wechat_copilot/tree.md"

echo "✅ tree.md 已生成"

# 生成新的 README.md - 项目概况
{
    echo "# WeChat Copilot 项目概况"
    echo ""
    echo "## 项目概述"
    echo ""
    echo "WeChat Copilot 是一个集成了 RPA（机器人流程自动化）、AI 大模型和 Web 界面的微信助手系统。该项目支持微信消息的自动捕获、AI 分析和回复，并提供 Web 界面进行管理和监控。"
    echo ""
    echo "## 核心功能"
    echo ""
    echo "### 1. RPA 自动化引擎"
    echo "- 微信窗口激活和控制"
    echo "- 屏幕截图和 OCR 文字识别"
    echo "- UI 元素定位和点击"
    echo "- 消息区域自动识别"
    echo ""
    echo "### 2. AI 智能分析"
    echo "- 多模态 AI（豆包）：UI 界面分析"
    echo "- 本地 LLM（Ollama）：普通对话处理"
    echo "- 豆包大模型：特殊技能和复杂任务处理"
    echo "- AI 路由：智能分配到合适的模型"
    echo ""
    echo "### 3. 后端服务"
    echo "- FastAPI 框架"
    echo "- SQLite 数据库"
    echo "- 用户和消息管理"
    echo "- SOP 规则引擎"
    echo ""
    echo "### 4. 前端界面"
    echo "- Vue3 + Vite"
    echo "- Naive UI 组件库"
    echo "- 用户管理和消息查看"
    echo "- RPA 操作监控"
    echo ""
    echo "## 项目进度"
    echo ""
    echo "### ✅ 已完成功能"
    echo "- [x] RPA 微信操作引擎"
    echo "- [x] OCR 文字识别系统"
    echo "- [x] AI 模型集成（豆包多模态、本地LLM）"
    echo "- [x] FastAPI 后端服务"
    echo "- [x] Vue3 前端界面"
    echo "- [x] 数据库设计和管理"
    echo "- [x] 用户和消息管理 API"
    echo "- [x] RPA 控制 API"
    echo "- [x] UI 分析 API"
    echo "- [x] 消息处理 API"
    echo "- [x] AI 路由系统"
    echo "- [x] 多模态 UI 分析"
    echo "- [x] 系统启动和管理脚本"
    echo ""
    echo "### 🔄 开发中功能"
    echo "- [ ] 消息推送实时通知"
    echo "- [ ] 群组消息处理"
    echo "- [ ] 文件传输功能"
    echo "- [ ] 高级 SOP 规则引擎"
    echo ""
    echo "### 📋 待开发功能"
    echo "- [ ] 语音消息处理"
    echo "- [ ] 视频消息处理"
    echo "- [ ] 数据统计和报表"
    echo "- [ ] 性能监控面板"
    echo ""
    echo "## 技术架构"
    echo ""
    echo "\`\`\`"
    echo "前端: Vue3 + Vite + Naive UI + Vue Router"
    echo "后端: FastAPI + SQLModel + SQLite"
    echo "AI模型: 豆包多模态 + 本地Ollama + AI路由"
    echo "RPA: xdotool + maim + PaddleOCR"
    echo "部署: 系统服务脚本 + 环境配置"
    echo "\`\`\`"
    echo ""
    echo "## 快速开始"
    echo ""
    echo "1. 安装依赖 (参考 INSTALL.md)"
    echo "2. 配置 API 密钥"
    echo "3. 启动系统: ./start_all.sh"
    echo "4. 访问前端: http://localhost:3000"
    echo "5. 访问 API 文档: http://localhost:8001/docs"
    echo ""
    echo "## 项目特点"
    echo ""
    echo "- 🚀 Arch Linux 兼容性"
    echo "- 🗄️ SQLite 轻量级数据库"
    echo "- 🤖 多模型 AI 集成"
    echo "- 🎨 现代化前端界面"
    echo "- 🔧 完整的 RPA 自动化"
    echo "- 📊 全面的监控和管理"
} > "/home/neogh/wechat_copilot/README.md"

echo "✅ README.md 已生成"

# 生成新的 INSTALL.md - 安装指南
{
    echo "# WeChat Copilot 安装指南"
    echo ""
    echo "## 系统要求"
    echo ""
    echo "### 硬件要求"
    echo "- CPU: 4 核以上 (推荐 8 核)"
    echo "- 内存: 8GB 以上 (推荐 16GB)"
    echo "- 存储: 10GB 可用空间"
    echo "- GPU: 可选 (用于本地AI模型加速)"
    echo ""
    echo "### 操作系统"
    echo "- Arch Linux (主要支持)"
    echo "- Ubuntu 20.04+ (兼容)"
    echo "- 其他 Linux 发行版 (需手动配置)"
    echo ""
    echo "## 软件依赖"
    echo ""
    echo "### 系统工具"
    echo "\`\`\`bash"
    echo "# Arch Linux"
    echo "sudo pacman -S python nodejs npm git xdotool maim curl wget"
    echo ""
    echo "# Ubuntu/Debian"
    echo "sudo apt update && sudo apt install python3 nodejs npm git xdotool maim curl wget"
    echo "\`\`\`"
    echo ""
    echo "### Python 依赖"
    echo "\`\`\`txt"
    echo "fastapi==0.104.1"
    echo "uvicorn==0.24.0"
    echo "sqlmodel==0.0.8"
    echo "paddleocr==2.6.0.1"
    echo "paddlepaddle==2.4.2"
    echo "requests==2.31.0"
    echo "numpy==1.24.3"
    echo "opencv-python==4.8.1.78"
    echo "apScheduler==3.10.4"
    echo "python-multipart==0.0.6"
    echo "cryptography==41.0.7"
    echo "python-dotenv==1.0.0"
    echo "\`\`\`"
    echo ""
    echo "### Node.js 依赖"
    echo "\`\`\`txt"
    echo "vue@^3.4.0"
    echo "vue-router@^4.3.0"
    echo "naive-ui@^2.38.0"
    echo "axios@^1.6.0"
    echo "vite@^5.0.0"
    echo "@vitejs/plugin-vue@^5.0.0"
    echo "\`\`\`"
    echo ""
    echo "## 安装步骤"
    echo ""
    echo "### 1. 克隆项目"
    echo "\`\`\`bash"
    echo "git clone <your-repo-url>"
    echo "cd wechat_copilot"
    echo "\`\`\`"
    echo ""
    echo "### 2. 安装 Python 依赖"
    echo "\`\`\`bash"
    echo "python -m venv .venv"
    echo "source .venv/bin/activate"
    echo "pip install --upgrade pip"
    echo "pip install -r requirements.txt"
    echo "\`\`\`"
    echo ""
    echo "### 3. 安装 Node.js 依赖"
    echo "\`\`\`bash"
    echo "cd frontend"
    echo "npm install"
    echo "\`\`\`"
    echo ""
    echo "### 4. 安装 Ollama (可选)"
    echo "\`\`\`bash"
    echo "# 下载并安装 Ollama"
    echo "curl -fsSL https://ollama.ai/install.sh | sh"
    echo ""
    echo "# 启动 Ollama 服务"
    echo "systemctl enable ollama --now"
    echo ""
    echo "# 拉取本地模型"
    echo "ollama pull qwen:7b-chat-q4_0"
    echo "\`\`\`"
    echo ""
    echo "### 5. 配置 API 密钥"
    echo "\`\`\`bash"
    echo "# 编辑 .env 文件"
    echo "cp .env.example .env"
    echo "vim .env  # 填入豆包API密钥等"
    echo "\`\`\`"
    echo ""
    echo "### 6. 初始化数据库"
    echo "\`\`\`bash"
    echo "cd backend"
    echo "source ../.venv/bin/activate"
    echo "python -c \"from db.session import create_tables; create_tables()\""
    echo "\`\`\`"
    echo ""
    echo "### 7. 启动服务"
    echo "\`\`\`bash"
    echo "# 启动完整系统"
    echo "./start_all.sh"
    echo ""
    echo "# 或分别启动"
    echo "# 后端: cd backend && uvicorn main:app --host 0.0.0.0 --port 8001"
    echo "# 前端: cd frontend && npm run dev"
    echo "\`\`\`"
    echo ""
    echo "## 验证安装"
    echo ""
    echo "### 检查服务状态"
    echo "\`\`\`bash"
    echo "# 检查后端"
    echo "curl http://localhost:8001/health"
    echo ""
    echo "# 检查前端"
    echo "curl http://localhost:3000"
    echo "\`\`\`"
    echo ""
    echo "### 访问界面"
    echo "- 前端界面: http://localhost:3000"
    echo "- API 文档: http://localhost:8001/docs"
    echo ""
    echo "## 故障排除"
    echo ""
    echo "### 常见问题"
    echo ""
    echo "1. **端口被占用**"
    echo "   - 检查并终止占用端口的进程: sudo fuser -k 8001/tcp"
    echo ""
    echo "2. **依赖安装失败**"
    echo "   - 确保网络连接正常"
    echo "   - 检查 Python 版本 (建议 3.11+)"
    echo ""
    echo "3. **Ollama 服务未启动**"
    echo "   - 检查服务状态: systemctl status ollama"
    echo "   - 手动启动: systemctl start ollama"
    echo ""
    echo "4. **API 密钥错误**"
    echo "   - 确认 .env 文件中的 API 密钥正确"
    echo "   - 检查 API 密钥是否有效"
    echo ""
    echo "## 性能优化建议"
    echo ""
    echo "- 使用 SSD 存储提高 I/O 性能"
    echo "- 确保充足的内存避免交换"
    echo "- GPU 加速本地 AI 模型 (如适用)"
    echo "- 定期清理日志文件"
} > "/home/neogh/wechat_copilot/INSTALL.md"

echo "✅ INSTALL.md 已生成"

# 生成新的 ProjectFramework.md - 框架完成情况
{
    echo "# WeChat Copilot 项目框架完成情况"
    echo ""
    echo "## 原始项目框架回顾"
    echo ""
    echo "### 初始设计目标"
    echo "- RPA引擎：微信自动化操作，包括窗口控制、消息捕获、界面分析等"
    echo "- AI集成：多模型支持，包括本地模型、云端模型和多模态模型"
    echo "- 后端服务：FastAPI框架，用户管理、消息存储、SOP规则等"
    echo "- 前端界面：Vue3界面，用户交互、监控显示、配置管理等"
    echo "- 数据库：SQLite轻量级数据库，用户、消息、规则等数据存储"
    echo ""
    echo "## 当前完成情况分析"
    echo ""
    echo "### ✅ 已完成模块"
    echo ""
    echo "#### 1. RPA 核心引擎"
    echo "- [x] **微信窗口控制** - 通过 xdotool 实现窗口激活、最小化、最大化"
    echo "- [x] **屏幕截图功能** - 使用 maim 实现精确区域截图"
    echo "- [x] **OCR 文字识别** - 集成 PaddleOCR 进行中文识别"
    echo "- [x] **UI 元素定位** - 坐标系统和元素识别功能"
    echo "- [x] **自动化操作** - 模拟点击、输入等操作"
    echo "- [x] **消息区域识别** - 自动识别聊天消息区域"
    echo ""
    echo "#### 2. AI 智能模块"
    echo "- [x] **多模态模型集成** - 豆包多模态模型用于UI分析"
    echo "- [x] **本地LLM集成** - Ollama + qwen:7b-chat-q4_0"
    echo "- [x] **AI 路由系统** - 根据内容智能分配到合适模型"
    echo "- [x] **意图识别** - 关键词检测和意图分类"
    echo "- [x] **对话管理** - 上下文维护和对话历史"
    echo "- [x] **UI 分析能力** - 识别界面元素及其位置"
    echo ""
    echo "#### 3. 后端服务"
    echo "- [x] **FastAPI 框架** - RESTful API 设计"
    echo "- [x] **数据库模型** - SQLModel 定义用户、消息、SOP规则"
    echo "- [x] **用户管理 API** - 用户增删改查、信息管理"
    echo "- [x] **消息管理 API** - 消息存储、查询、删除"
    echo "- [x] **SOP 规则 API** - 标准操作程序规则管理"
    echo "- [x] **RPA 控制 API** - 微信操作接口"
    echo "- [x] **UI 分析 API** - 界面分析接口"
    echo "- [x] **消息处理 API** - AI消息处理接口"
    echo ""
    echo "#### 4. 前端界面"
    echo "- [x] **Vue3 框架** - 使用 Composition API"
    echo "- [x] **路由系统** - Vue Router 页面导航"
    echo "- [x] **UI 组件库** - Naive UI 组件"
    echo "- [x] **用户列表页** - 显示和管理用户"
    echo "- [x] **用户详情页** - 用户信息和消息历史"
    echo "- [x] **API 集成** - 与后端服务通信"
    echo "- [x] **状态管理** - 响应式数据绑定"
    echo ""
    echo "#### 5. 系统集成"
    echo "- [x] **环境配置** - .env 配置文件"
    echo "- [x] **启动脚本** - 一键启动前后端服务"
    echo "- [x] **监控脚本** - 系统状态检查"
    echo "- [x] **部署脚本** - 完整系统部署"
    echo "- [x] **日志管理** - 服务日志记录和查看"
    echo "- [x] **进程管理** - 服务启停控制"
    echo ""
    echo "### 🔄 开发中模块"
    echo ""
    echo "#### 1. 高级功能"
    echo "- [ ] **实时消息推送** - WebSocket 实时通知"
    echo "- [ ] **群组消息处理** - 群聊消息识别和处理"
    echo "- [ ] **文件传输** - 图片、文档等文件处理"
    echo "- [ ] **语音消息** - 语音转文字和文字转语音"
    echo ""
    echo "#### 2. 系统优化"
    echo "- [ ] **性能监控** - 系统资源使用监控"
    echo "- [ ] **缓存优化** - Redis 缓存机制"
    echo "- [ ] **负载均衡** - 多实例部署支持"
    echo "- [ ] **安全增强** - API 认证和授权"
    echo ""
    echo "### 📋 待开发模块"
    echo ""
    echo "#### 1. 扩展功能"
    echo "- [ ] **数据分析** - 消息统计和分析报表"
    echo "- [ ] **工作流引擎** - 复杂业务流程自动化"
    echo "- [ ] **多语言支持** - 国际化功能"
    echo "- [ ] **插件系统** - 可扩展功能模块"
    echo ""
    echo "#### 2. 运维工具"
    echo "- [ ] **备份恢复** - 数据备份和恢复机制"
    echo "- [ ] **升级工具** - 自动化升级流程"
    echo "- [ ] **配置管理** - 集中化配置管理"
    echo "- [ ] **监控告警** - 系统健康检查和告警"
    echo ""
    echo "## 技术栈总结"
    echo ""
    echo "### 前端技术栈"
    echo "- Vue3: 前端框架，Composition API"
    echo "- Vite: 构建工具，快速开发体验"
    echo "- Naive UI: 组件库，现代化界面设计"
    echo "- Axios: HTTP 客户端，API 请求处理"
    echo "- Vue Router: 路由管理，页面导航"
    echo ""
    echo "### 后端技术栈"
    echo "- FastAPI: Web 框架，高性能 API 开发"
    echo "- SQLModel: ORM 框架，数据库操作"
    echo "- SQLite: 轻量级数据库，数据存储"
    echo "- uvicorn: ASGI 服务器，应用部署"
    echo "- Pydantic: 数据验证，类型检查"
    echo ""
    echo "### AI 技术栈"
    echo "- 豆包多模态: UI 分析和图像理解"
    echo "- Ollama: 本地大语言模型服务"
    echo "- PaddleOCR: 光学字符识别"
    echo "- 自定义路由: 智能模型选择"
    echo ""
    echo "### RPA 技术栈"
    echo "- xdotool: X11 窗口控制"
    echo "- maim: 屏幕截图工具"
    echo "- subprocess: 系统命令调用"
    echo "- APScheduler: 任务调度"
    echo ""
    echo "## 项目里程碑"
    echo ""
    echo "### M1: 核心功能实现"
    echo "- [x] RPA 基础功能"
    echo "- [x] AI 集成"
    echo "- [x] 前后端基础架构"
    echo "- [x] 数据库设计"
    echo ""
    echo "### M2: 功能完善"
    echo "- [x] UI 分析功能"
    echo "- [x] 消息处理流程"
    echo "- [x] 系统集成测试"
    echo "- [x] 部署脚本"
    echo ""
    echo "### M3: 产品化"
    echo "- [ ] 性能优化"
    echo "- [ ] 用户体验优化"
    echo "- [ ] 文档完善"
    echo "- [ ] 部署方案"
    echo ""
    echo "### M4: 扩展功能"
    echo "- [ ] 高级特性"
    echo "- [ ] 企业级功能"
    echo "- [ ] 生态集成"
    echo "- [ ] 商业化准备"
    echo ""
    echo "## 当前版本状态: Alpha -> Beta 过渡阶段"
    echo ""
    echo "- ✅ 核心功能已完成，可正常运行"
    echo "- ✅ API 接口稳定，文档完善"
    echo "- ✅ 前端界面可用，用户体验良好"
    echo "- 🔄 性能优化和稳定性提升中"
    echo "- 📋 高级功能正在规划和开发"
} > "/home/neogh/wechat_copilot/ProjectFramework.md"

echo "✅ ProjectFramework.md 已生成"

echo ""
echo "----------------------------------------"
echo "项目整理完成！"
echo "----------------------------------------"
echo "📁 新生成的文件:"
echo "   tree.md - 项目文件结构"
echo "   README.md - 项目概况和进度"
echo "   INSTALL.md - 安装指南和依赖"
echo "   ProjectFramework.md - 框架完成情况"
echo ""
echo "📝 备份日志: edit.logs"
echo ""
echo "🎉 项目整理和文档生成完成！"